export const siteConfig = {
  name: "Manvendra Rajpoot",
  shortName: "Manvendra",
  jobTitle: "Backend Developer",
  // Full résumé headline — used for OG image, hero, and rich phrasing.
  roleline: "Backend Developer · Automation & AI · Cloud Engineering",
  tagline:
    "Backend developer building scalable, secure, AI-powered systems and robust APIs.",
  description:
    "Manvendra Rajpoot is a backend developer specializing in AI automation, robust API design, and cloud engineering. He builds scalable, secure, multi-tenant systems with Python, Django, DRF, FastAPI, PostgreSQL, Redis, Docker, and Kubernetes. Explore projects, experience, and get in touch.",
  url: "https://www.rajpoot.dev",
  ogImage: "/opengraph-image",
  email: "manvendra@rajpoot.dev",
  locale: "en_US",
  language: "en",
  location: {
    city: "Jaipur",
    region: "Rajasthan",
    country: "India",
    countryCode: "IN",
  },
  twitter: "@AlzyWelzy",
  github: "https://github.com/AlzyWelzy",
  linkedin: "https://linkedin.com/in/AlzyWelzy",
  // Highlighted stack used in the OG image card.
  ogTags: ["Python", "Django", "FastAPI", "PostgreSQL", "Docker", "Kubernetes"],
  keywords: [
    "Manvendra Rajpoot",
    "Manvendra Rajpoot Portfolio",
    "Manvendra Rajpoot Backend Developer",
    "Backend Developer",
    "Backend Developer Portfolio",
    "Python Developer",
    "Django Developer",
    "Django REST Framework Developer",
    "FastAPI Developer",
    "API Developer",
    "AI Automation Developer",
    "Cloud Engineer",
    "DevOps Engineer",
    "Docker",
    "Kubernetes",
    "PostgreSQL",
    "Microservices Developer",
    "SaaS Developer",
    "Full Stack Developer",
    "Next.js Developer",
    "React Developer",
    "TypeScript Developer",
    "Software Developer India",
    "alzywelzy",
    "Alzy Welzy",
    "rajpoot.dev",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
