#!/usr/bin/env node
/**
 * Builds the progressive-enhancement bundle — the only JavaScript the site
 * ships.
 *
 * Why esbuild and not Vite: with `csr = false` SvelteKit emits no client build
 * for this script to be an entry point of, and SvelteKit owns the Vite config
 * besides. esbuild bundling one module is a few lines and adds no build-time
 * dependency that isn't already installed (Vite depends on esbuild).
 *
 * The output is content-hashed, so it can be cached immutably like any other
 * build asset. The filename is written to src/lib/generated/enhance-url.ts,
 * which the layout imports and renders into a <script> tag at prerender time —
 * that indirection is what keeps the hash out of hand-written markup.
 *
 * Runs BEFORE `vite build`: the generated constant has to exist before
 * SvelteKit typechecks and prerenders, and the hashed file has to be in
 * static/ before the adapter copies it.
 */
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(root, "src/lib/enhance/index.ts");
const OUT_DIR = join(root, "static/_enhance");
const GENERATED = join(root, "src/lib/generated/enhance-url.ts");

const result = await build({
  entryPoints: [ENTRY],
  bundle: true,
  minify: true,
  format: "esm",
  // The CSP has no `script-src 'unsafe-eval'` and the site targets evergreen
  // browsers; es2022 keeps the output small and avoids helper shims.
  target: "es2022",
  platform: "browser",
  write: false,
  legalComments: "none",
  define: {
    // `$env/static/public` belongs to SvelteKit's Vite pipeline, which this
    // bundle is built outside of. Baking the value in lets esbuild eliminate
    // the analytics body entirely when no endpoint is configured, which is the
    // current deployed state.
    __ANALYTICS_ENDPOINT__: JSON.stringify(
      process.env.PUBLIC_ANALYTICS_ENDPOINT ?? "",
    ),
  },
});

const [output] = result.outputFiles;
if (!output) throw new Error("gen-enhance: esbuild produced no output");

const code = output.contents;
const hash = createHash("sha256").update(code).digest("hex").slice(0, 8);
const fileName = `enhance.${hash}.js`;

// Drop stale hashes so the directory doesn't accumulate one file per edit.
if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true });
mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, fileName), code);

const url = `/_enhance/${fileName}`;
const contents = `// Generated by scripts/gen-enhance.mjs — do not edit by hand.
// URL of the progressive-enhancement bundle, content-hashed so it can be
// served immutably. Imported by src/routes/+layout.svelte and rendered into a
// <script> tag at prerender time.
export const enhanceUrl = "${url}" as const;
`;

mkdirSync(dirname(GENERATED), { recursive: true });
const existing = existsSync(GENERATED) ? readFileSync(GENERATED, "utf8") : null;
if (existing !== contents) writeFileSync(GENERATED, contents);

const bytes = code.byteLength;
console.log(`[gen-enhance] ${url} (${bytes} bytes minified)`);

// Sanity check: this bundle exists to be tiny. If it ever isn't, that is a
// design regression worth failing the build over rather than discovering in a
// Lighthouse report weeks later.
const BUDGET = 20_000;
if (bytes > BUDGET) {
  console.error(
    `[gen-enhance] bundle is ${bytes} bytes, over the ${BUDGET} byte budget.\n` +
      `The whole point of csr:false is that this stays small — if the site now\n` +
      `genuinely needs this much client code, reconsider the architecture\n` +
      `rather than raising the number.`,
  );
  process.exit(1);
}

// Nothing else should be writing here.
const stray = readdirSync(OUT_DIR).filter((f) => f !== fileName);
if (stray.length) throw new Error(`gen-enhance: unexpected files ${stray}`);
